cat > .github/workflows/build-aab.yml << 'EOF'
name: Build Iona Wallet AAB
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: 33.0.0
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Build AAB
        env:
          STATUS_GO_SRC_OVERRIDE: ${{ github.workspace }}/statusgo
        run: |
          echo "Building with StatusGO: $STATUS_GO_SRC_OVERRIDE"
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease
      
      - name: Upload AAB
        uses: actions/upload-artifact@v3
        with:
          name: iona-wallet-aab
          path: android/app/build/outputs/bundle/release/app-release.aab
EOF
