name: Build Iona Wallet AAB
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0
          ndk-version: 25.1.8937393
      
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      
      - name: Setup Nix
        uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          
      - name: Setup Cachix
        uses: cachix/cachix-action@v12
        with:
          name: status-im
          
      - name: Enter Nix shell and install dependencies
        run: |
          nix-shell --run "make status-go-library"
        
      - name: Setup StatusGO environment
        run: |
          echo "STATUS_GO_SRC_OVERRIDE=${{ github.workspace }}/statusgo" >> $GITHUB_ENV
          echo "STATUS_GO_ANDROID_LIBDIR=${{ github.workspace }}/statusgo" >> $GITHUB_ENV
          
      - name: Prepare Android build
        run: |
          cd android
          chmod +x gradlew
          
      - name: Create debug keystore (for testing)
        run: |
          cd android/app
          keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
          
      - name: Build AAB (Debug)
        run: |
          cd android
          ./gradlew bundleDebug --stacktrace
          
      - name: Build AAB (Release - unsigned)
        run: |
          cd android
          ./gradlew bundleRelease --stacktrace
          
      - name: Upload Debug AAB
        uses: actions/upload-artifact@v4
        with:
          name: iona-wallet-debug-aab
          path: android/app/build/outputs/bundle/debug/app-debug.aab
          
      - name: Upload Release AAB
        uses: actions/upload-artifact@v4
        with:
          name: iona-wallet-release-aab
          path: android/app/build/outputs/bundle/release/app-release.aab
          
      - name: List build outputs
        run: |
          echo "Debug AAB:"
          ls -la android/app/build/outputs/bundle/debug/ || echo "Debug bundle not found"
          echo "Release AAB:"
          ls -la android/app/build/outputs/bundle/release/ || echo "Release bundle not found"